/**
 * Security audit log types and Zod schemas.
 *
 * All security events are validated against these schemas before being
 * appended to the immutable audit log (data/audit/security.jsonl).
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Event types
// ---------------------------------------------------------------------------

export const AuditEventTypeSchema = z.enum([
  'guard.pass',
  'guard.block',
  'secret.access',
  'secret.proxy_fetch',
  'secret.proxy_blocked',
  'pii.redact',
  'approval.request',
  'approval.result',
  'posture.change',
]);
export type AuditEventType = z.infer<typeof AuditEventTypeSchema>;

// ---------------------------------------------------------------------------
// Per-type detail schemas
// ---------------------------------------------------------------------------

export const GuardPassDetailsSchema = z.object({
  action: z.string(),
  toolName: z.string().optional(),
  guardsChecked: z.number(),
});
export type GuardPassDetails = z.infer<typeof GuardPassDetailsSchema>;

export const GuardBlockDetailsSchema = z.object({
  action: z.string(),
  toolName: z.string().optional(),
  guardName: z.string(),
  reason: z.string(),
});
export type GuardBlockDetails = z.infer<typeof GuardBlockDetailsSchema>;

export const SecretAccessDetailsSchema = z.object({
  key: z.string(),
  operation: z.enum(['get', 'set', 'delete', 'list']),
  agentId: z.string().optional(),
});
export type SecretAccessDetails = z.infer<typeof SecretAccessDetailsSchema>;

export const SecretProxyFetchDetailsSchema = z.object({
  key: z.string(),
  url: z.string(),
  method: z.string(),
});
export type SecretProxyFetchDetails = z.infer<typeof SecretProxyFetchDetailsSchema>;

export const SecretProxyBlockedDetailsSchema = z.object({
  key: z.string(),
  url: z.string(),
  reason: z.string(),
});
export type SecretProxyBlockedDetails = z.infer<typeof SecretProxyBlockedDetailsSchema>;

export const PiiRedactDetailsSchema = z.object({
  fieldsRedacted: z.number(),
  rulesApplied: z.array(z.string()),
  hash: z.string(),
});
export type PiiRedactDetails = z.infer<typeof PiiRedactDetailsSchema>;

export const ApprovalRequestDetailsSchema = z.object({
  requestId: z.string(),
  action: z.string(),
  channel: z.string().optional(),
  description: z.string().optional(),
});
export type ApprovalRequestDetails = z.infer<typeof ApprovalRequestDetailsSchema>;

export const ApprovalResultDetailsSchema = z.object({
  requestId: z.string(),
  approved: z.boolean(),
  timedOut: z.boolean(),
  latencyMs: z.number(),
});
export type ApprovalResultDetails = z.infer<typeof ApprovalResultDetailsSchema>;

export const PostureChangeDetailsSchema = z.object({
  from: z.string(),
  to: z.string(),
  changedBy: z.string(),
});
export type PostureChangeDetails = z.infer<typeof PostureChangeDetailsSchema>;

// ---------------------------------------------------------------------------
// Unified event schema
// ---------------------------------------------------------------------------

export const AuditEventSchema = z.object({
  id: z.string().uuid(),
  type: AuditEventTypeSchema,
  timestamp: z.string().datetime(),
  agentId: z.string().optional(),
  sessionId: z.string().optional(),
  details: z.record(z.unknown()),
  /** HMAC of the previous event in the chain (tamper detection). */
  prevHash: z.string().optional(),
  /** HMAC-SHA256 of this event including prevHash (tamper detection). */
  hash: z.string().optional(),
});
export type AuditEvent = z.infer<typeof AuditEventSchema>;

/**
 * Input for creating an audit event. The `id`, `timestamp`, `prevHash`,
 * and `hash` are auto-generated by the audit log implementation.
 */
export type AuditEventInput = Omit<AuditEvent, 'id' | 'timestamp' | 'prevHash' | 'hash'>;

// ---------------------------------------------------------------------------
// Query filter
// ---------------------------------------------------------------------------

export interface AuditFilter {
  type?: AuditEventType;
  agentId?: string;
  since?: string;
  until?: string;
  limit?: number;
}

// ---------------------------------------------------------------------------
// Audit log interface
// ---------------------------------------------------------------------------

export interface AuditLog {
  /** Append a security event. Never fails silently. */
  append(event: AuditEventInput): void;
  /** Query events with optional filters. */
  query(filter?: AuditFilter): Promise<AuditEvent[]>;
}
