/** Common symbol → company name lookup for auto-complete. */
const SYMBOL_NAMES: Record<string, string> = {
  // ── Mega-cap / Big Tech ──
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft Corp.',
  GOOGL: 'Alphabet Inc.',
  GOOG: 'Alphabet Inc.',
  AMZN: 'Amazon.com Inc.',
  META: 'Meta Platforms Inc.',
  NVDA: 'NVIDIA Corp.',
  TSLA: 'Tesla Inc.',
  BRK: 'Berkshire Hathaway',
  'BRK.B': 'Berkshire Hathaway',
  'BRK.A': 'Berkshire Hathaway',

  // ── Financials ──
  JPM: 'JPMorgan Chase',
  V: 'Visa Inc.',
  MA: 'Mastercard Inc.',
  BAC: 'Bank of America',
  WFC: 'Wells Fargo',
  GS: 'Goldman Sachs',
  MS: 'Morgan Stanley',
  BLK: 'BlackRock Inc.',
  SCHW: 'Charles Schwab',
  AXP: 'American Express',
  C: 'Citigroup Inc.',
  USB: 'U.S. Bancorp',
  PNC: 'PNC Financial',
  COF: 'Capital One',
  CME: 'CME Group',
  ICE: 'Intercontinental Exchange',
  SPGI: 'S&P Global',
  MCO: "Moody's Corp.",
  CB: 'Chubb Ltd.',
  MMC: 'Marsh & McLennan',
  AON: 'Aon plc',
  MET: 'MetLife Inc.',
  PRU: 'Prudential Financial',
  AIG: 'American Intl Group',
  TFC: 'Truist Financial',

  // ── Healthcare ──
  UNH: 'UnitedHealth Group',
  JNJ: 'Johnson & Johnson',
  LLY: 'Eli Lilly',
  PFE: 'Pfizer Inc.',
  MRK: 'Merck & Co.',
  ABT: 'Abbott Labs',
  TMO: 'Thermo Fisher',
  ABBV: 'AbbVie Inc.',
  DHR: 'Danaher Corp.',
  BMY: 'Bristol-Myers Squibb',
  AMGN: 'Amgen Inc.',
  GILD: 'Gilead Sciences',
  MDT: 'Medtronic plc',
  ISRG: 'Intuitive Surgical',
  SYK: 'Stryker Corp.',
  VRTX: 'Vertex Pharma',
  REGN: 'Regeneron Pharma',
  ZTS: 'Zoetis Inc.',
  CI: 'Cigna Group',
  ELV: 'Elevance Health',
  HCA: 'HCA Healthcare',
  BSX: 'Boston Scientific',
  EW: 'Edwards Lifesciences',
  MRNA: 'Moderna Inc.',
  DXCM: 'DexCom Inc.',
  IQV: 'IQVIA Holdings',
  A: 'Agilent Technologies',
  BDX: 'Becton Dickinson',
  BIIB: 'Biogen Inc.',

  // ── Technology ──
  ADBE: 'Adobe Inc.',
  CRM: 'Salesforce Inc.',
  AMD: 'Advanced Micro Devices',
  INTC: 'Intel Corp.',
  AVGO: 'Broadcom Inc.',
  CSCO: 'Cisco Systems',
  ORCL: 'Oracle Corp.',
  ACN: 'Accenture plc',
  TXN: 'Texas Instruments',
  QCOM: 'Qualcomm Inc.',
  IBM: 'IBM Corp.',
  NOW: 'ServiceNow Inc.',
  INTU: 'Intuit Inc.',
  AMAT: 'Applied Materials',
  LRCX: 'Lam Research',
  MU: 'Micron Technology',
  ADI: 'Analog Devices',
  SNPS: 'Synopsys Inc.',
  CDNS: 'Cadence Design',
  KLAC: 'KLA Corp.',
  PANW: 'Palo Alto Networks',
  CRWD: 'CrowdStrike Holdings',
  FTNT: 'Fortinet Inc.',
  NET: 'Cloudflare Inc.',
  MRVL: 'Marvell Technology',
  NXPI: 'NXP Semiconductors',
  TEAM: 'Atlassian Corp.',
  WDAY: 'Workday Inc.',
  ZS: 'Zscaler Inc.',
  DDOG: 'Datadog Inc.',
  SNOW: 'Snowflake Inc.',
  MDB: 'MongoDB Inc.',
  HUBS: 'HubSpot Inc.',
  TTD: 'The Trade Desk',
  DELL: 'Dell Technologies',
  HPQ: 'HP Inc.',
  HPE: 'Hewlett Packard Enterprise',
  ARM: 'Arm Holdings',
  SMCI: 'Super Micro Computer',
  MSTR: 'MicroStrategy Inc.',
  PLTR: 'Palantir Technologies',
  IOT: 'Samsara Inc.',

  // ── Consumer / Retail ──
  WMT: 'Walmart Inc.',
  PG: 'Procter & Gamble',
  COST: 'Costco Wholesale',
  HD: 'Home Depot',
  NKE: 'Nike Inc.',
  DIS: 'Walt Disney Co.',
  NFLX: 'Netflix Inc.',
  PEP: 'PepsiCo Inc.',
  KO: 'Coca-Cola Co.',
  MCD: "McDonald's Corp.",
  SBUX: 'Starbucks Corp.',
  TGT: 'Target Corp.',
  LOW: "Lowe's Companies",
  TJX: 'TJX Companies',
  ROST: 'Ross Stores',
  CMG: 'Chipotle Mexican Grill',
  YUM: 'Yum! Brands',
  EL: 'Estée Lauder',
  CL: 'Colgate-Palmolive',
  KMB: 'Kimberly-Clark',
  GIS: 'General Mills',
  K: 'Kellanova',
  HSY: 'Hershey Co.',
  KHC: 'Kraft Heinz',
  MDLZ: 'Mondelez Intl',
  STZ: 'Constellation Brands',
  PM: 'Philip Morris Intl',
  MO: 'Altria Group',
  LULU: 'Lululemon Athletica',
  DECK: 'Deckers Outdoor',
  ON: 'ON Semiconductor',
  ABNB: 'Airbnb Inc.',

  // ── Payments / Fintech ──
  PYPL: 'PayPal Holdings',
  SQ: 'Block Inc.',
  COIN: 'Coinbase Global',
  SHOP: 'Shopify Inc.',
  AFRM: 'Affirm Holdings',
  SOFI: 'SoFi Technologies',
  HOOD: 'Robinhood Markets',
  FIS: 'Fidelity Natl Info',
  FISV: 'Fiserv Inc.',
  GPN: 'Global Payments',

  // ── Industrials ──
  CAT: 'Caterpillar Inc.',
  DE: 'Deere & Company',
  UNP: 'Union Pacific',
  HON: 'Honeywell Intl',
  UPS: 'United Parcel Service',
  BA: 'Boeing Co.',
  RTX: 'RTX Corp.',
  LMT: 'Lockheed Martin',
  GE: 'GE Aerospace',
  GEV: 'GE Vernova',
  MMM: 'Minnesota Mining (3M)',
  EMR: 'Emerson Electric',
  ITW: 'Illinois Tool Works',
  ETN: 'Eaton Corp.',
  FDX: 'FedEx Corp.',
  CSX: 'CSX Corp.',
  NSC: 'Norfolk Southern',
  WM: 'Waste Management',
  RSG: 'Republic Services',
  PH: 'Parker Hannifin',
  ROK: 'Rockwell Automation',
  CARR: 'Carrier Global',
  UBER: 'Uber Technologies',
  LYFT: 'Lyft Inc.',
  DAL: 'Delta Air Lines',
  UAL: 'United Airlines',
  LUV: 'Southwest Airlines',

  // ── Energy ──
  XOM: 'Exxon Mobil',
  CVX: 'Chevron Corp.',
  COP: 'ConocoPhillips',
  SLB: 'Schlumberger Ltd.',
  EOG: 'EOG Resources',
  MPC: 'Marathon Petroleum',
  PSX: 'Phillips 66',
  VLO: 'Valero Energy',
  OXY: 'Occidental Petroleum',
  HAL: 'Halliburton Co.',
  DVN: 'Devon Energy',
  FANG: 'Diamondback Energy',

  // ── Utilities / Real Estate ──
  NEE: 'NextEra Energy',
  DUK: 'Duke Energy',
  SO: 'Southern Company',
  D: 'Dominion Energy',
  AEP: 'American Electric Power',
  SRE: 'Sempra Energy',
  PLD: 'Prologis Inc.',
  AMT: 'American Tower',
  CCI: 'Crown Castle Intl',
  EQIX: 'Equinix Inc.',
  PSA: 'Public Storage',
  SPG: 'Simon Property Group',
  O: 'Realty Income',
  WELL: 'Welltower Inc.',
  DLR: 'Digital Realty',

  // ── Communication ──
  T: 'AT&T Inc.',
  VZ: 'Verizon Communications',
  TMUS: 'T-Mobile US',
  CMCSA: 'Comcast Corp.',
  CHTR: 'Charter Communications',

  // ── Autos / EV ──
  F: 'Ford Motor Co.',
  GM: 'General Motors',
  RIVN: 'Rivian Automotive',
  LCID: 'Lucid Group',
  NIO: 'NIO Inc.',
  LI: 'Li Auto Inc.',
  XPEV: 'XPeng Inc.',

  // ── Social / Internet ──
  SNAP: 'Snap Inc.',
  PINS: 'Pinterest Inc.',
  RDDT: 'Reddit Inc.',
  RBLX: 'Roblox Corp.',
  U: 'Unity Software',
  ROKU: 'Roku Inc.',
  SPOT: 'Spotify Technology',
  SE: 'Sea Limited',
  BABA: 'Alibaba Group',
  JD: 'JD.com Inc.',
  PDD: 'PDD Holdings',
  BIDU: 'Baidu Inc.',
  GRAB: 'Grab Holdings',

  // ── ETFs ──
  SPY: 'SPDR S&P 500 ETF',
  QQQ: 'Invesco QQQ Trust',
  IWM: 'iShares Russell 2000',
  VOO: 'Vanguard S&P 500',
  VTI: 'Vanguard Total Market',
  ARKK: 'ARK Innovation ETF',
  GLD: 'SPDR Gold Shares',
  DIA: 'SPDR Dow Jones ETF',
  IVV: 'iShares Core S&P 500',
  VEA: 'Vanguard FTSE Developed',
  VWO: 'Vanguard FTSE Emerging',
  EFA: 'iShares MSCI EAFE',
  EEM: 'iShares MSCI Emerging',
  AGG: 'iShares Core US Bond',
  BND: 'Vanguard Total Bond',
  TLT: 'iShares 20+ Year Treasury',
  HYG: 'iShares High Yield Corp',
  LQD: 'iShares Investment Grade',
  XLF: 'Financial Select SPDR',
  XLK: 'Technology Select SPDR',
  XLE: 'Energy Select SPDR',
  XLV: 'Health Care Select SPDR',
  XLI: 'Industrial Select SPDR',
  XLP: 'Consumer Staples SPDR',
  XLY: 'Consumer Discretionary SPDR',
  XLU: 'Utilities Select SPDR',
  XLRE: 'Real Estate Select SPDR',
  XLC: 'Communication Services SPDR',
  XLB: 'Materials Select SPDR',
  VGT: 'Vanguard Info Tech ETF',
  SCHD: 'Schwab US Dividend ETF',
  JEPI: 'JPMorgan Equity Premium',
  JEPQ: 'JPMorgan Nasdaq Premium',
  VIG: 'Vanguard Dividend Appreciation',
  SOXX: 'iShares Semiconductor ETF',
  SMH: 'VanEck Semiconductor ETF',
  IBIT: 'iShares Bitcoin Trust',
  BITB: 'Bitwise Bitcoin ETF',
  FBTC: 'Fidelity Wise Origin Bitcoin',
  ARKB: 'ARK 21Shares Bitcoin ETF',
  ETHE: 'Grayscale Ethereum Trust',
  GBTC: 'Grayscale Bitcoin Trust',
  SLV: 'iShares Silver Trust',
  USO: 'United States Oil Fund',
  UNG: 'United States Natural Gas',
  KWEB: 'KraneShares CSI China Internet',
  TQQQ: 'ProShares UltraPro QQQ',
  SQQQ: 'ProShares UltraPro Short QQQ',
  SOXL: 'Direxion Semiconductor Bull 3X',

  // ── Crypto ──
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  SOL: 'Solana',
  DOGE: 'Dogecoin',
  ADA: 'Cardano',
  XRP: 'Ripple',
  DOT: 'Polkadot',
  AVAX: 'Avalanche',
  MATIC: 'Polygon',
  POL: 'Polygon',
  LINK: 'Chainlink',
  UNI: 'Uniswap',
  AAVE: 'Aave',
  ATOM: 'Cosmos',
  LTC: 'Litecoin',
  BCH: 'Bitcoin Cash',
  ALGO: 'Algorand',
  FIL: 'Filecoin',
  NEAR: 'NEAR Protocol',
  APT: 'Aptos',
  ARB: 'Arbitrum',
  OP: 'Optimism',
  SUI: 'Sui',
  SEI: 'Sei',
  TIA: 'Celestia',
  INJ: 'Injective',
  RENDER: 'Render Network',
  FET: 'Fetch.ai',
  RNDR: 'Render Token',
  PEPE: 'Pepe',
  SHIB: 'Shiba Inu',
  WIF: 'dogwifhat',
  BONK: 'Bonk',
  JUP: 'Jupiter',
  PYTH: 'Pyth Network',
  W: 'Wormhole',
  STRK: 'Starknet',
  MKR: 'Maker',
  CRV: 'Curve DAO',
  LDO: 'Lido DAO',
  SNX: 'Synthetix',
  COMP: 'Compound',
  ENS: 'Ethereum Name Service',
  SAND: 'The Sandbox',
  MANA: 'Decentraland',
  AXS: 'Axie Infinity',
  IMX: 'Immutable X',
  GRT: 'The Graph',
  FTM: 'Fantom',
  HBAR: 'Hedera',
  VET: 'VeChain',
  XLM: 'Stellar',
  EOS: 'EOS',
  XTZ: 'Tezos',
  THETA: 'Theta Network',
  EGLD: 'MultiversX',
  FLOW: 'Flow',
  MINA: 'Mina Protocol',
  USDT: 'Tether',
  USDC: 'USD Coin',
  DAI: 'Dai',
};

export function lookupSymbolName(symbol: string): string {
  return SYMBOL_NAMES[symbol.toUpperCase().trim()] ?? '';
}
