/** Common symbol → company name lookup for auto-complete. */
const SYMBOL_NAMES: Record<string, string> = {
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft Corp.',
  GOOGL: 'Alphabet Inc.',
  AMZN: 'Amazon.com Inc.',
  META: 'Meta Platforms Inc.',
  NVDA: 'NVIDIA Corp.',
  TSLA: 'Tesla Inc.',
  BRK: 'Berkshire Hathaway',
  JPM: 'JPMorgan Chase',
  V: 'Visa Inc.',
  JNJ: 'Johnson & Johnson',
  WMT: 'Walmart Inc.',
  PG: 'Procter & Gamble',
  MA: 'Mastercard Inc.',
  UNH: 'UnitedHealth Group',
  HD: 'Home Depot',
  DIS: 'Walt Disney Co.',
  BAC: 'Bank of America',
  ADBE: 'Adobe Inc.',
  CRM: 'Salesforce Inc.',
  NFLX: 'Netflix Inc.',
  AMD: 'Advanced Micro Devices',
  INTC: 'Intel Corp.',
  PYPL: 'PayPal Holdings',
  CSCO: 'Cisco Systems',
  PEP: 'PepsiCo Inc.',
  AVGO: 'Broadcom Inc.',
  COST: 'Costco Wholesale',
  TMO: 'Thermo Fisher',
  ABT: 'Abbott Labs',
  NKE: 'Nike Inc.',
  MRK: 'Merck & Co.',
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  SOL: 'Solana',
  DOGE: 'Dogecoin',
  ADA: 'Cardano',
  XRP: 'Ripple',
  DOT: 'Polkadot',
  AVAX: 'Avalanche',
  MATIC: 'Polygon',
  LINK: 'Chainlink',
  COIN: 'Coinbase Global',
  SQ: 'Block Inc.',
  SHOP: 'Shopify Inc.',
  UBER: 'Uber Technologies',
  ABNB: 'Airbnb Inc.',
  SNAP: 'Snap Inc.',
  PLTR: 'Palantir Technologies',
  RIVN: 'Rivian Automotive',
  SPY: 'SPDR S&P 500 ETF',
  QQQ: 'Invesco QQQ Trust',
  IWM: 'iShares Russell 2000',
  VOO: 'Vanguard S&P 500',
  VTI: 'Vanguard Total Market',
  ARKK: 'ARK Innovation ETF',
  GLD: 'SPDR Gold Shares',
};

export function lookupSymbolName(symbol: string): string {
  return SYMBOL_NAMES[symbol.toUpperCase().trim()] ?? '';
}
